export const actionIds = {
    // TEST
    TEST_ACTION: 'test action',

    // SHOP LIST
    GET_SHOP_LISTS: 'shopList/GET_SHOP_LISTS',
    GET_SHOP_LISTS_SUCCESS: 'shopList/GET_SHOP_LISTS_SUCCESS',
    GET_SHOP_LISTS_FAIL: 'shopList/GET_SHOP_LISTS_FAIL',
    GET_SHOP_LISTS_NORMALIZED: 'shopList/GET_SHOP_LISTS/NORMALIZED',

    CREATE_SHOP_LISTS: 'shopList/CREATE_SHOP_LISTS',
    CREATE_SHOP_LISTS_SUCCESS: 'shopList/CREATE_SHOP_LISTS_SUCCESS',
    CREATE_SHOP_LISTS_FAIL: 'shopList/CREATE_SHOP_LISTS_FAIL',

    // STORE
    GET_STORE_LIST: 'store/GET_STORE_LIST',
    GET_STORE_LIST_SUCCESS: 'store/GET_STORE_LIST_SUCCESS',
    GET_STORE_LIST_FAIL: 'store/GET_STORE_LIST_FAIL',
    GET_STORE_LIST_NORMALIZED: 'store/GET_STORE_LIST/NORMALIZED',
};
